### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by boratanrikulu** [ozanyerli/turkeyvisited#1]
The map is not loaded in Firefox (93).

![Screenshot_2021-10-18_00-51-13](https://user-images.githubusercontent.com/20258973/137646269-4cf9d038-2b5f-4db4-8eb6-ea487e14c578.png)

**Comment by ozanyerli** [comment]
The issue was weirdly caused by using d3 function .style({ 'attrName1' : 'attrValue1', 'attrName2' : 'attrValue2' (and so on...) }) instead of .attr('attrName', 'attrValue'). It's fixed now.
