### ISSUE TITLE
Ziyaret edilen il sayısının gösterimi

### ISSUE THREAD

**Issue by msc314** [ozanyerli/turkeyvisited#2]
Emeğinize sağlık Ozan Bey. Güzel bir çalışma olmuş.
Ziyaret edilen il sayısının gösterimi de eklenebilirse çok güzel olur diye düşünüyorum.

**Comment by ozanyerli** [comment]
Teşekkür ederim, bu özelliği belki de katkıda bulunmak isteyen başka arkadaşlar ekleyebilirler, iyi bir first issue olabilir.

**Comment by FlySquare** [comment]
merhaba, ben bu issue üzerinde geliştirme yaptım. dilerseniz kontrol edebilirsiniz. https://github.com/ozanyerli/turkeyvisited/pull/4
