### ISSUE TITLE
Seçili olan illeri temizleme butonu

### ISSUE THREAD

**Issue by ozanyerli** [ozanyerli/turkeyvisited#8]
localStorage'i temizleyerek haritada seçili olan illeri sıfırlayıp haritayı ilk haline getiren ufak bir temizleme butonu kullanışlı olabilir.

**Comment by samilboyalikli** [comment]
Selamlar.

Yeni yolladığım req'te local'i ve sayfadaki counter'ı sıfırlayan bir reset butonu ekledim: #9

Projenin kendisi üzerinde çalışamayıp yalnızca elimdeki fork üzerinde çalışabildiğim için `Bölgeler` butonuyla alakalı kodları kaldırmadım. `Bölgeler` butonunun olmadığı, `Sıfırla` butonunun olduğu yeni bir req yollayacağım.

**Comment by samilboyalikli** [comment]
Selamlar.

`Bölgeler` butonunun olmadığı ve yalnızca `Sıfırla` butonunun olduğu bir request yolladım: #10

**Comment by samilboyalikli** [comment]
`Sıfırla` butonunun yukarıda olduğu, github logosunun da daha sağda olduğu bir hali için: #11
